[build]
target = "index.html"
dist = "dist"

[watch]
watch = ["src", "index.html"]

[serve]
address = "127.0.0.1"
port = 8084
open = false

[[hooks]]
stage = "post_build"
command = "sh"
command_arguments = ["-c", "echo 'Build complete!'"]
